#!groovy

// Generated by IBM TransformationAdvisor
// Thu Mar 07 12:40:27 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}